domain: sekitmc.github.io       
url: https://sekitmc.github.io  
remote_theme: pages-themes/slate@v0.2.0
plugins: 
- jekyll-remote-theme

title: sekit-mc
description: Free minecraft java server builder
